[package]
name = "editor"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.11.2"
bevy_flycam = { path = "../../lib/bevy_flycam"}
bevy_iron_ui = { path = "../../lib/bevy_iron_ui"}
bevy_iron_voxel = { path = "../../lib/bevy_iron_voxel"}
